version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_NETWORK_ID=1
      - NEXT_PUBLIC_NETWORK_NAME=mainnet
    depends_on:
      - backend
    networks:
      - blocpol-network

  backend:
    image: blocpol-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - blocpol-network

networks:
  blocpol-network:
    driver: bridge
